vehicle:
  name: "custom_vehicle"
  type: "UGV"

actuators:
  motors:
    - id: 1
      type: "brushless"
      interface: "CAN"
      max_rpm: 6000
      can_id: 10
    - id: 2
      type: "brushed"
      interface: "PWM"
      pwm_channel: 3
  servos:
    - id: 1
      type: "steering"
      interface: "PWM"
      pwm_channel: 2
      min_angle: -30
      max_angle: 30

sensors:
  imu:
    model: "MPU6050"
    interface: "I2C"
    i2c_address: 0x68
    topic: "/imu/data"
  gps:
    model: "Ublox M8N"
    interface: "UART"
    port: "/dev/ttyUSB0"
    baudrate: 115200
    topic: "/gps/fix"
  lidar:
    model: "RPLidar A2"
    interface: "USB"
    port: "/dev/ttyUSB1"
    baudrate: 115200
    topic: "/scan"

ros_nodes:
  localization:
    package: "robot_localization"
    node: "ekf_localization"
    parameters:
      use_imu: true
      use_gps: true
      imu_topic: "/imu/data"
      gps_topic: "/gps/fix"
  motion_control:
    package: "vehicle_control"
    node: "motion_controller"
    parameters:
      max_speed: 2.0
      steering_limit: 30
    remap:
      cmd_vel: "/vehicle/cmd_vel"
  perception:
    package: "lidar_processing"
    node: "lidar_node"
    parameters:
      min_range: 0.1
      max_range: 12.0
    remap:
      lidar_scan: "/scan"

network:
  ros_master_uri: "http://localhost:11311"
  use_sim_time: false
